- name: Remove default site (optional)
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - Test nginx config
    - Reload nginx

- name: Place NGINX site config
  template:
    src: flaskapp.conf.j2
    dest: /etc/nginx/sites-available/{{ app_name }}.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Test nginx config
    - Reload nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/{{ app_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ app_name }}.conf
    state: link
  notify:
    - Test nginx config
    - Reload nginx

- name: Validate nginx config (pre-start)
  command: nginx -t
  register: nginx_config_test
  changed_when: false

- name: Show nginx -t output
  debug:
    var: nginx_config_test.stderr_lines

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
